# serverless.yml

service: discord-gpt-4-bot

frameworkVersion: '3'

useDotenv: true

plugins:
    - serverless-esbuild
    - serverless-offline

custom:
    esbuild:
        packager: pnpm
        plugins: esbuildWasmPlugin.cjs
        watch:
            pattern: ['src/**/*.ts', 'dids.ts']

provider:
    name: aws
    runtime: nodejs16.x
    timeout: 900
    stage: ${opt:stage, "dev"}
    region: ${opt:region, "us-west-2"}
    environment:
        LAMBDA_STAGE: ${opt:stage, "dev"}
        DISCORD_TOKEN: ${env:DISCORD_TOKEN}
        DISCORD_APPLICATION_KEY: ${env:DISCORD_APPLICATION_KEY}
        APPLICATION_ID: ${env:APPLICATION_ID}
        GUILD_ID: ${env:GUILD_ID}
        CHANNEL_ID: ${env:CHANNEL_ID}
        OPENAI_API_TOKEN: ${env:OPENAI_API_TOKEN}
        KEYV_URL: ${env:KEYV_URL}

    tracing:
        apiGateway: true
        lambda: true
    httpApi:
        cors:
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: '*'

functions:
    discord:
        handler: lambda.discordHandler
        events:
            - httpApi: ANY /{params+}
        url:
            cors: true
